<a href="https://colab.research.google.com/github/keyasaurabh/Data-Science--Cheat-Sheet/blob/master/Python_For_Data_Science_NUMPY_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
### numpy arrays

In [0]:
### casting any list to an array

In [0]:
my_list1 = [1,2,3,4,5,5,7]
my_list2 = [1,2,3,3,4,5,6]
### in list you can chnage the value
my_list2[0]=9
my_list2

In [0]:
import numpy as np

In [0]:
mylstarr1 = np.array(my_list1)

In [0]:
mylstarr2 = np.array(my_list2)

In [5]:
mylstarr1/mylstarr2

array([1.        , 1.        , 1.        , 1.33333333, 1.25      ,
       1.        , 1.16666667])

In [0]:
arr = np.array(my_list1)
arr
print(arr)

In [69]:
arr.sum()### you cannot do for list

27

In [0]:
### casting any list to a matrix

In [0]:
my_mat =  [[1,2,3],[4,5,6],[7,8,9]]

In [0]:
np.array(my_mat)

In [64]:
np.sum(my_mat) ###sum of all no

45

In [0]:
## np range function ==similar to python range

In [10]:
np.arange(0,11,2)   ### creates an array from 0 thru 11 in steps of 2. note, 11 is excluded here.

array([ 0,  2,  4,  6,  8, 10])

In [30]:
np.array([1,2],dtype=int)

array([1, 2])

In [0]:
###to generate array of zeros

In [11]:
np.zeros(3)  ## 2 dimensional array
 

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
#### arrays of ones
print(np.ones(4))
print('\n')
print(np.ones((2,3)))


[1. 1. 1. 1.]


[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
np.zeros((3,3,3))  ### 3 dimensional array by giving a tuple within np.array command

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
### creating empty array. not much of a use. caution to be exercised
arrempt1=np.empty((2,3))
arrempt1           ##### creates random numbers...

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
###3 linearly (Equal) sapced data elements
np.linspace(4,15,12)  

### outputs a 2d array with number of evenly spaced points from 0 to 5. 10 indicates the number of such points

array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.])

In [0]:
##identity matrix

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(10)  ### creates one dim array of 10 evenly random numbers between 0 and 10 excluding 0 and 1
np.random()


array([0.8159357 , 0.73024186, 0.92455996, 0.84563509, 0.96009067,
       0.34129466, 0.5488559 , 0.47086438, 0.84512799, 0.69511189])

In [0]:
np.random.randint(1,100)  ### returns random integer from 1 to 100. includes 1 and excludes 100

64

In [0]:
np.random.randn(1,10)

array([[-0.06652894, -1.57074937,  2.27126977,  0.24725484,  1.1193266 ,
         0.35210431,  1.9868602 ,  0.90100778,  0.12191711,  0.63347925]])

In [0]:
np.random.randint(1,100,10)  ### returns 10 random integer from 1 to 100 

array([98, 27, 99, 34, 28, 47, 84, 79,  2, 25])

In [0]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
arr.ndim

1

In [0]:
ranarr1 = np.random.randint(0,50,10)
ranarr1

array([ 0, 36, 15, 28, 14, 26,  0, 43, 41, 14])

In [0]:
print(arr.shape)

print(type(arr.shape))

(25,)
<class 'tuple'>


In [0]:
arr.ndim

1

In [0]:
print(arr.size)
print(type(arr.size))

25
<class 'int'>


In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
print(arr.ndim)

1


In [0]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
arr.reshape(5,5).argmax()

24

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
print(arr.ndim)

1


In [0]:
#print(arr.re)

In [0]:
arr_2d.ndim

2

In [0]:
print(ranarr1)
print(ranarr1.max())

[ 0 36 15 28 14 26  0 43 41 14]
43


In [0]:
ranarr1.min()

0

In [0]:
print(ranarr1)
print(ranarr1.argmax())

[ 0 36 15 28 14 26  0 43 41 14]
7


In [0]:
ranarr1.argmin()

0

In [0]:
#### to find the dimension of an array
np_city =  np.array(['nyc','la','houston'])

In [51]:
np_city.ndim

1

In [52]:
len(np_city)

3

In [53]:
np_city.shape           #### gives the length and the dimension of array

(3,)

In [0]:
np_countries = np.array([['brazil','portugal','morrocco'],['egypt','iran','spain'],['russia','uae','argentina']])

In [55]:
np_countries.shape

(3, 3)

In [56]:
np_countries.ndim

2

In [57]:
np_countries.size

9

In [58]:
np_city.size

3

In [0]:
len(np_countries)  ##### gives me the length of 2 dimensional array which is 3 lists

In [0]:
np_city.shape

In [0]:
np_countries.dtype

dtype('<U9')

In [36]:
import numpy as np
x=[1,2,3]
#a=np.asarray(x)
a= np.array(x)
print(a)

[1 2 3]


In [0]:
my_arr1 = np.arange(25)

In [38]:
my_arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
my_arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
##### indexing and slicing with 2 dimensional array

In [0]:
array_2d = np.array([[5,10,15],[20,25,30],[34,49,29]])

In [0]:
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [34, 49, 29]])

In [0]:
#### if we want to extract 10,15,25,30 from the 2d array
print(array_2d[:1,1:])



[[10 15]]


In [0]:
print(array_2d[1:])

[[20 25 30]
 [34 49 29]]


In [0]:
array_2d[1:,1:]

array([[25, 30],
       [49, 29]])

In [0]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float) ##convert other non float to float

In [32]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [0]:
#### three dim arrary

In [0]:
threeD_array = np.arange(27).reshape(3,3,3)

In [34]:
threeD_array        #### watch for number of square brackets in the resulting list

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [0]:
##selecting elements from the array

In [40]:
print(my_arr1)
my_arr1[20]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


20

In [41]:
my_arr1[1:5]   ##3 always returns one less than the end item (5) 

array([1, 2, 3, 4])

In [42]:
my_arr1[2:5]   ## returns elements of 1st row from 2nd index (0,1,2) to 5th index. 5th excluded

array([2, 3, 4])

In [43]:
my_arr1[:9]   # selects everthting upto index 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
my_arr1[0:] # selects everything from index 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
my_arr1[5:]  ## select everything beyond index 5 ..note value 4 is in index 5 here

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [0]:
my_arr_3 = np.arange(25)

In [0]:
my_arr_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
slice_my_arr3 = my_arr_3[1:5]

In [0]:
slice_my_arr3

array([1, 2, 3, 4])

In [0]:
my_arr_3[1:5] = 100 

In [0]:
my_arr_3

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [0]:
slice_my_arr3

array([100, 100, 100, 100])

In [0]:
my_arr_4 = np.arange(30)
print(my_arr_4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [0]:
slice_arr4 = my_arr_4[0:6]
print(slice_arr4)

[0 1 2 3 4 5]


In [0]:
my_arr_4[0:6] = 500   ##
print(my_arr_4)

[500 500 500 500 500 500   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29]


In [0]:
print(slice_arr4)

[500 500 500 500 500 500]


In [0]:
slice_my_arr3

array([100, 100, 100, 100])

In [0]:
##broadcasting

In [0]:
my_arr1[0:5] = 999  ### broadcasts all the elements upto index 5 to 999

In [0]:
slice_my_arr = my_arr1[-1]  

In [0]:
my_arr1

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [0]:
slice_my_arr

24

In [0]:
my_arr1   ### note that the change done to slice_my_arr has also impacted my_arr

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [0]:
copy_my_arr = my_arr1.copy()   ### copies my_arr to copy_my_arr
copy_my_arr

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [0]:
copy_my_arr[:] = 999
copy_my_arr

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999,
       999, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [0]:
my_arr1     ## no change

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [0]:
### creating 2d arrays

In [0]:
my_arr_2d = np.arange(50)

In [0]:
my_arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [49]:
my_arr_2d =np.arange(50).reshape(5,10)
my_arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [0]:
#my_arr_2d=np.arange(50)
#my_arr_2d.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [0]:
my_arr_2d    ### a 2 dimensional array or matrix is created by first using arange function and then 
             #####            reshaping the array to a matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [0]:
my_arr_2d[0][0]   ### double bracket notation. gives me value in 1st row 1st col

0

In [0]:
my_arr_2d[0,0]     #### single bracket notation. recommended

0

In [0]:
my_arr_2d[0]    ### returns the entire 1st row 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
my_arr_2d[1,1]   ## returns the value in the 2nd row 2nd col (remember everything starts with 0)

11

In [0]:
my_arr_2d[1][1]   ### gives the same answer as above, but this is double bracket notation

11

In [0]:
my_arr_2d[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [0]:
my_arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [0]:
my_arr_2d [1:2,1:10]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [0]:
my_arr_2d[0:5,3:10]

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49]])

In [0]:
my_arr_2d[0:5,0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [0]:
my_arr_2d[my_arr_2d < 47]  ### gives me everything less than 47
#my_arr_2d < 47  ### gives me everything less than 47

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46])

In [0]:
my_arr_2d[my_arr_2d <=16]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [0]:
a

In [0]:
pwd

In [0]:
my_list

In [0]:
nparr

In [0]:
my_matrix

In [0]:
np.array(my_matrix)

In [0]:
np.arange(0,11)

In [0]:
np.floor

In [0]:
np.random.randn(10)          #### returns numbers from a standard normal distribution .keeps changing everytime you execute it

In [0]:
np.random.randn(4,4)        #### w dimensional random 

In [0]:
np.random.randint(1,100,10)            #### low=1, high=100. high is exclusive, 10-gives number of random int 
                                       ##keeps changing between 1 and 100 everytime you execute it

In [0]:
arr = np.arange(25)
arr

In [0]:
ranarr = np.random.randint(0,50,10)

In [0]:
ranarr

In [0]:
# geenerate random numbers
np.random.rand(5)

In [0]:
np.random.rand(5,5)

In [0]:
## returns from normal dist or guassian dis
np.random.randn(2)

In [0]:
np.random.randn(2,2)

In [0]:
np.random.randint(1,100)   ### gives integer from low number to high number. low inclusive, high exclusive

In [0]:
np.random.randint(1,100,10)   ### gives me 10 random integers from low number to high numbner..low inc,.high excl


In [0]:
ranarr.max()

In [0]:
ranarr.min()

In [0]:
ranarr.argmax()            ### returns the index location of max value

In [0]:
ranarr.argmin()           ### returns the index location of min value

In [0]:
##### hint
#### instead of typing np.random.randint you can do the below
from numpy.random import randint


In [0]:
randint(2,10)

NameError: name 'randint' is not defined

In [0]:
ranarr2 = np.arange(20) 

In [0]:
ranarr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
np.floor(ranarr2)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [0]:
ranarr3=np.arange(30)

In [0]:
 np